package dev.pocketprl

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long

/** Loads app/src/test/resources/pearl_vectors.json (generated by tools/vectors/gen-vectors.sh). */
object Vectors {
    val root: JsonObject by lazy {
        val text = Vectors::class.java.getResourceAsStream("/pearl_vectors.json")!!.bufferedReader().readText()
        Json.parseToJsonElement(text).jsonObject
    }

    val shake256: JsonArray get() = root.getValue("shake256").jsonArray
    val xmss: JsonArray get() = root.getValue("xmss").jsonArray
    val hkdf: JsonArray get() = root.getValue("hkdf").jsonArray
    val bip32: JsonArray get() = root.getValue("bip32").jsonArray
    val wallets: List<JsonObject> get() = root.getValue("wallets").jsonArray.map { it.jsonObject }
}

fun JsonObject.str(k: String): String = getValue(k).jsonPrimitive.content
fun JsonObject.int(k: String): Int = getValue(k).jsonPrimitive.int
fun JsonObject.long(k: String): Long = getValue(k).jsonPrimitive.long
fun JsonObject.arr(k: String): List<JsonObject> = getValue(k).jsonArray.map { it.jsonObject }
fun JsonObject.objOrNull(k: String): JsonObject? = get(k)?.let { if (it is JsonObject) it else null }
